# Generated by Django 4.2 on 2023-05-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('fixed', 'Fixed'), ('range', 'Range')], default='fixed', max_length=10)),
                ('salary_from', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
